# This file is part of ASAP.
# Please see LICENSE.txt for copyright and licensing information.

LEVEL = ../../..
LIBRARYNAME = SanityChecks
LOADABLE_MODULE = 1
USEDLIBS =

include $(LEVEL)/Makefile.common
